version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: xazar-postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5400:5432
    env_file:
      - database.env # configure postgres


#  # port 5400
#
#  # run command : docker-compose up -d
#
